# Generated by Django 5.0.6 on 2024-07-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='renk',
            new_name='rank',
        ),
    ]
